[W3B-41] Feat/weather station nft
WeatherXM/smart-contracts pull request #27
Opened 2023-07-19 20:43 UTC by NikosFotiadis

2023-07-20 11:51 UTC, tmavroeid commented
Add some documentation for WeatherXMStation NFT in the docs.

2023-07-20 12:33 UTC, tmavroeid reviewed
Add some documentation for WeatherXMStation NFT in the docs.

2023-07-20 12:39 UTC, tmavroeid commented on src/WeatherXMStation.sol
> +    tokenMetadata[stationId].decomissioned = true;
Given the token owner it can be resolved if it is Claimed or Unclaimed, so the current implementation fits our use case.

2023-07-20 13:14 UTC, tmavroeid commented on package.json
> +		"web3": "^4.0.3"
I don't think that this tradeoff is worth the value of adding and using a whole new framework instead the one already used for a bunch of operations. Due to time constraints, its probably best to move on and later revisit and remove web3 framework.

2023-07-20 13:22 UTC, NikosFotiadis commented on package.json
> +		"web3": "^4.0.3"
We can revisit this in a new PR for the tests so that we are not blocking the code. I am adding a note about this.

2023-07-20 13:37 UTC, tmavroeid requested changes

2023-07-20 13:37 UTC, tmavroeid commented on src/WeatherXMStation.sol
> +    tokenMetadata[newItemId].model = model;
Why not check the WeatherXMStationsRegistry if model arg is valid?

2023-07-20 13:39 UTC, NikosFotiadis commented on src/WeatherXMStation.sol
> +    tokenMetadata[newItemId].model = model;
Right. Will add now that we merged #28

2023-07-20 14:46 UTC, tmavroeid approved these changes

2023-07-21 08:18 UTC, tmavroeid approved these changes

2023-07-21 12:04 UTC, merged